import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/providers/TranslationsProvider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { t, resources, i18n } = await initTranslations(params.locale, [
    "dashboard",
  ]);
  return (
    <html dir={i18n.language === "ar" ? "rtl" : "ltr"}>
      <body className={roboto.className}>
        <TranslationsProvider
          locale={params.locale}
          namespaces={["dashboard"]}
          resources={resources}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
